### PR TITLE
feat: proper documentation of Named Destinations

### PR DESCRIPTION
**Pull request by yohgen**
This is a solution to an (non-)issue I've filed in the main `react-pdf` repo: diegomura/react-pdf#2110
1. Added proper [Named Destinations](https://pdfkit.org/docs/destinations.html) documentation with an example
2. Combined **Destinations** and **Bookmarks** sections in **Advanced** page into a single section called **Document Navigation**
3. Renamed and changed **Bookmarks** page link in `Menu` to **Document Navigation**
4. Added `id` prop to `Page`, `View`, and `Text` elements in **Components** page (as per [types](https://github.com/diegomura/react-pdf/tree/master/packages/types))
5. Added destination name to `Link`'s `src` prop definition in **Components** page

### CODE REVIEW

**Comment by yohgen** [comment]
@diegomura Sorry to disturb you, but is there any particular reason why my PR is being ignored? (Rather than accepted, rejected, or subjected to modifications, that is). Are there guidelines that I failed to follow?

**Review by diegomura — APPROVED** [review]
Thanks! Looks great

**Comment by diegomura** [comment]
@yohgen sorry, wasn't ignored 😄 Just didn't have the bandwidth to review it. Thanks for taking the time to enhance this

**Comment by yohgen** [comment]
@diegomura No problem, thank you for taking your time to review!

**Comment by bartoszgrzyb** [comment]
There is an issue with the example, actually the `Link` should have leading hash:
`<Link src='#Footnote'>`

and `Text` should be without - it acts like anchors in HTML

 `<Text id='Footnote'>`

**Comment by diegomura** [comment]
@yohgen mind fixing it?

**Comment by yohgen** [comment]
@diegomura @bartoszgrzyb Yeah, my bad, I'll fix it asap

**Comment by yohgen** [comment]
Made a PR with fixes: #102

**Pull request merged**
