### PR TITLE
fix: broken line in hyphenation.md

### PR DESCRIPTION
**Pull request by imatwork**
I think I updated the link to go to the right place but please double check.

Thanks for the wonderful library!

### CODE REVIEW

**Comment by imatwork** [comment]
Hmm, the more I look at this file the more Im convinced this isn't the right link. It doesn't have the same `(word)=>[word]` signature, even though the above section mentions the Knuth-Plass algorithm.

Maybe https://github.com/diegomura/react-pdf/blob/master/packages/textkit/src/engines/wordHyphenation/index.js is right? Im not sure... Sorry

**Comment by diegomura** [comment]
Yes @imatwork ! That last one is the right. I'll merge this once you change it 😄 Thanks for this find

**Comment by imatwork** [comment]
Good to go

**Review by diegomura — APPROVED** [review]
Thanks!

**Pull request merged**
